"""Clinical lab-marker reference knowledge base.

General adult reference ranges with plain-language explanations. Ranges are
typical adult values and can vary by lab, sex, and age — the UI states this.
This is the data behind the medical-report analyzer; no LLM required.
"""
from __future__ import annotations

# Each marker:
#   key, name, aliases (lowercase; matched in text), unit, low, high, category,
#   about (plain meaning), high_note, low_note, advice, related (risk model id or "")
#   exclude_prefix: tokens that, if immediately before an alias, disqualify the match
MARKERS: list[dict] = [
    # ---- Metabolic ----
    {"key": "glucose_fasting", "name": "Fasting Glucose", "unit": "mg/dL", "low": 70, "high": 99,
     "aliases": ["fasting blood glucose", "fasting blood sugar", "fasting glucose", "glucose fasting", "glucose (fasting)", "fbs", "blood sugar (fasting)", "glucose"],
     "category": "Metabolic", "about": "Blood sugar measured after fasting; a primary screen for diabetes.",
     "high_note": "Readings of 100–125 suggest prediabetes and 126+ suggest diabetes.",
     "low_note": "Low fasting glucose can cause shakiness, sweating, or dizziness.",
     "advice": "Limit refined sugar and simple carbs, stay active, and consider an HbA1c test.", "related": "diabetes"},
    {"key": "hba1c", "name": "HbA1c", "unit": "%", "low": 4.0, "high": 5.6,
     "aliases": ["hba1c", "hemoglobin a1c", "glycated hemoglobin", "glycosylated hemoglobin", "a1c"],
     "category": "Metabolic", "about": "Average blood sugar over the past 2–3 months.",
     "high_note": "5.7–6.4% indicates prediabetes; 6.5% or higher indicates diabetes.",
     "low_note": "Unusually low values are uncommon and usually not a concern.",
     "advice": "Reduce sugar intake, increase activity, and discuss screening with your doctor.", "related": "diabetes"},
    # ---- Lipids ----
    {"key": "cholesterol_total", "name": "Total Cholesterol", "unit": "mg/dL", "low": 0, "high": 200,
     "aliases": ["total cholesterol", "cholesterol total", "cholesterol, total", "serum cholesterol", "cholesterol"],
     "category": "Lipids", "about": "Total amount of cholesterol in your blood.",
     "high_note": "200–239 is borderline high; 240+ is high and raises heart risk.",
     "low_note": "Low total cholesterol is usually not a concern.",
     "advice": "Reduce saturated fat, add soluble fiber, and stay active.", "related": "heart",
     "exclude_prefix": ["hdl", "ldl", "non-hdl", "non hdl", "vldl"]},
    {"key": "ldl", "name": "LDL Cholesterol", "unit": "mg/dL", "low": 0, "high": 100,
     "aliases": ["ldl cholesterol", "ldl-c", "ldl", "low density lipoprotein"],
     "category": "Lipids", "about": "“Bad” cholesterol that builds up in arteries.",
     "high_note": "100–159 is near/above optimal; 160+ is high and raises heart risk.",
     "low_note": "Low LDL is generally favorable.",
     "advice": "Cut saturated and trans fats; increase fiber and exercise.", "related": "heart"},
    {"key": "hdl", "name": "HDL Cholesterol", "unit": "mg/dL", "low": 40, "high": 200,
     "aliases": ["hdl cholesterol", "hdl-c", "hdl", "high density lipoprotein"],
     "category": "Lipids", "about": "“Good” cholesterol that helps clear other cholesterol.",
     "high_note": "Higher HDL is protective for the heart.",
     "low_note": "Below 40 is low and increases cardiovascular risk.",
     "advice": "Regular aerobic exercise and healthy fats (olive oil, nuts) raise HDL.", "related": "heart"},
    {"key": "triglycerides", "name": "Triglycerides", "unit": "mg/dL", "low": 0, "high": 150,
     "aliases": ["triglycerides", "triglyceride", "tg"],
     "category": "Lipids", "about": "A type of fat in the blood; energy stored from excess calories.",
     "high_note": "150–199 is borderline; 200+ is high and linked to heart and metabolic risk.",
     "low_note": "Low triglycerides are generally not a concern.",
     "advice": "Reduce sugar, refined carbs, and alcohol; increase omega-3 intake.", "related": "heart"},
    # ---- Complete blood count ----
    {"key": "hemoglobin", "name": "Hemoglobin", "unit": "g/dL", "low": 13.0, "high": 17.0,
     "aliases": ["hemoglobin", "haemoglobin", "hb", "hgb"],
     "category": "Blood Count", "about": "Protein in red blood cells that carries oxygen.",
     "high_note": "High hemoglobin can relate to dehydration or other conditions.",
     "low_note": "Low hemoglobin may indicate anemia (fatigue, paleness, weakness).",
     "advice": "If low, discuss iron/B12 testing and iron-rich foods with your doctor.", "related": ""},
    {"key": "wbc", "name": "White Blood Cells", "unit": "10³/µL", "low": 4.0, "high": 11.0,
     "aliases": ["white blood cell", "white blood cells", "wbc count", "wbc", "total leukocyte count", "tlc", "leukocytes"],
     "category": "Blood Count", "about": "Immune cells that fight infection.",
     "high_note": "High WBC can indicate infection, inflammation, or stress.",
     "low_note": "Low WBC can reduce the ability to fight infection.",
     "advice": "Interpret alongside symptoms; persistent abnormalities warrant follow-up.", "related": ""},
    {"key": "platelets", "name": "Platelets", "unit": "10³/µL", "low": 150, "high": 410,
     "aliases": ["platelet count", "platelets", "plt"],
     "category": "Blood Count", "about": "Cell fragments that help blood clot.",
     "high_note": "High platelets can increase clotting risk.",
     "low_note": "Low platelets can increase bruising and bleeding.",
     "advice": "Marked abnormalities should be reviewed by a clinician.", "related": ""},
    # ---- Kidney ----
    {"key": "creatinine", "name": "Creatinine", "unit": "mg/dL", "low": 0.6, "high": 1.3,
     "aliases": ["serum creatinine", "creatinine"],
     "category": "Kidney", "about": "A waste product filtered by the kidneys; reflects kidney function.",
     "high_note": "High creatinine can indicate reduced kidney function.",
     "low_note": "Low creatinine is usually not a concern.",
     "advice": "Stay hydrated; if elevated, discuss kidney-function testing (eGFR).", "related": ""},
    {"key": "urea", "name": "Blood Urea / BUN", "unit": "mg/dL", "low": 7, "high": 20,
     "aliases": ["blood urea nitrogen", "bun", "blood urea", "urea"],
     "category": "Kidney", "about": "A waste product that reflects kidney function and hydration.",
     "high_note": "High values can reflect dehydration or reduced kidney function.",
     "low_note": "Low values are usually not a concern.",
     "advice": "Maintain hydration; interpret with creatinine and eGFR.", "related": ""},
    {"key": "uric_acid", "name": "Uric Acid", "unit": "mg/dL", "low": 3.5, "high": 7.2,
     "aliases": ["uric acid"],
     "category": "Kidney", "about": "A waste product; high levels can cause gout.",
     "high_note": "High uric acid can lead to gout and kidney stones.",
     "low_note": "Low uric acid is usually not a concern.",
     "advice": "Limit red meat, organ meats, and alcohol; stay hydrated.", "related": ""},
    # ---- Liver ----
    {"key": "alt", "name": "ALT (SGPT)", "unit": "U/L", "low": 7, "high": 56,
     "aliases": ["alt (sgpt)", "sgpt", "alanine aminotransferase", "alt"],
     "category": "Liver", "about": "A liver enzyme; elevated levels can indicate liver stress.",
     "high_note": "High ALT can indicate liver inflammation or fatty liver.",
     "low_note": "Low ALT is generally not a concern.",
     "advice": "Limit alcohol, maintain a healthy weight, and avoid unnecessary medications.", "related": ""},
    {"key": "ast", "name": "AST (SGOT)", "unit": "U/L", "low": 5, "high": 40,
     "aliases": ["ast (sgot)", "sgot", "aspartate aminotransferase", "ast"],
     "category": "Liver", "about": "A liver (and muscle) enzyme used to assess liver health.",
     "high_note": "High AST can indicate liver or muscle stress.",
     "low_note": "Low AST is generally not a concern.",
     "advice": "Limit alcohol and interpret alongside ALT.", "related": ""},
    {"key": "bilirubin", "name": "Total Bilirubin", "unit": "mg/dL", "low": 0.1, "high": 1.2,
     "aliases": ["total bilirubin", "bilirubin total", "bilirubin"],
     "category": "Liver", "about": "A pigment processed by the liver.",
     "high_note": "High bilirubin can cause jaundice (yellowing of skin/eyes).",
     "low_note": "Low bilirubin is not a concern.",
     "advice": "Persistent elevation warrants liver-function follow-up.", "related": ""},
    # ---- Thyroid ----
    {"key": "tsh", "name": "TSH", "unit": "µIU/mL", "low": 0.4, "high": 4.0,
     "aliases": ["tsh", "thyroid stimulating hormone", "thyroid-stimulating hormone"],
     "category": "Thyroid", "about": "Hormone that regulates the thyroid gland.",
     "high_note": "High TSH can indicate an underactive thyroid (hypothyroidism).",
     "low_note": "Low TSH can indicate an overactive thyroid (hyperthyroidism).",
     "advice": "Discuss thyroid symptoms (weight, energy, temperature) with your doctor.", "related": ""},
    # ---- Vitamins ----
    {"key": "vitamin_d", "name": "Vitamin D (25-OH)", "unit": "ng/mL", "low": 30, "high": 100,
     "aliases": ["vitamin d", "25-hydroxyvitamin d", "25-oh vitamin d", "25 oh vitamin d", "vit d"],
     "category": "Vitamins", "about": "Supports bone health and immunity.",
     "high_note": "Very high levels from supplements can be harmful.",
     "low_note": "Below 30 is insufficient; below 20 is deficient (common and treatable).",
     "advice": "Sensible sun exposure and, if low, supplementation as advised by a clinician.", "related": ""},
    {"key": "vitamin_b12", "name": "Vitamin B12", "unit": "pg/mL", "low": 200, "high": 900,
     "aliases": ["vitamin b12", "vitamin b-12", "cobalamin", "b12"],
     "category": "Vitamins", "about": "Essential for nerves and red blood cell formation.",
     "high_note": "High B12 is usually from supplements and rarely a concern.",
     "low_note": "Low B12 can cause fatigue, tingling, and anemia.",
     "advice": "If low, discuss diet (or supplements) with your doctor, especially if vegetarian.", "related": ""},
    # ---- Electrolytes ----
    {"key": "sodium", "name": "Sodium", "unit": "mmol/L", "low": 135, "high": 145,
     "aliases": ["sodium", "na+", "serum sodium"],
     "category": "Electrolytes", "about": "An electrolyte that balances fluids and nerve function.",
     "high_note": "High sodium can relate to dehydration.",
     "low_note": "Low sodium can cause confusion, headache, or weakness.",
     "advice": "Interpret with hydration status; marked changes need review.", "related": ""},
    {"key": "potassium", "name": "Potassium", "unit": "mmol/L", "low": 3.5, "high": 5.1,
     "aliases": ["potassium", "k+", "serum potassium"],
     "category": "Electrolytes", "about": "An electrolyte vital for heart and muscle function.",
     "high_note": "High potassium can affect heart rhythm and needs prompt review.",
     "low_note": "Low potassium can cause weakness and cramps.",
     "advice": "Significant abnormalities should be reviewed by a clinician promptly.", "related": ""},
]

MARKER_BY_KEY = {m["key"]: m for m in MARKERS}
